### ISSUE TITLE
Useless `restic_env` file in home directory?

### ISSUE THREAD

**Issue by leumasic** [angristan/ansible-restic#12]
I'm really new to ansible but it seems like this `env` file
https://github.com/angristan/ansible-restic/blob/fd989a95b1cb379ae01c80f7d8fd19547443dea3/tasks/main.yml#L27-L33

isn't used. I don't see it sourced. Is it dead code or is it a special path restic reads from?

**Comment by angristan** [comment]
It contains `RESTIC_REPOSITORY` and `RESTIC_PASSWORD`. These two env variables are present in the systemd unit. However is use this file to do manual actions like:

```sh
source .restic_env
restic <action>
```

It's only for that :) But it's not used besides that

**Comment by leumasic** [comment]
Désolé, j'ai fermé ce ticket puisqu'il n'était pas si important.

Maintenant que j'y reviens, ma recommendation alors est d'enlever ce fichier de ce repo.

**Comment by angristan** [comment]
It's useful for me :)
