### ISSUE TITLE
Missing --exclude flag when exclude is specified

### ISSUE THREAD

**Issue by jadolg** [angristan/ansible-restic#13]
When a path has exclude, the `--exclude` flag should be specified in front of every parameter here.
The flag is currently missing: https://github.com/angristan/ansible-restic/blob/fd989a95b1cb379ae01c80f7d8fd19547443dea3/templates/restic-backup.service.j2#L27

**Comment by jadolg** [comment]
This should fix it https://github.com/angristan/ansible-restic/pull/14
Exclude could also be treated as a list instead of just one element but it's probably better not to break compatibility at least for now.

**Comment by angristan** [comment]
See README:


> Each folder has a `path` and an `exclude` property (which defaults to nothing). The `exclude` property is the literal argument passed to restic (exemple: `--exclude .cache --exclude .local`).

**Comment by angristan** [comment]
I don't remember why I did it that way though 🤔

**Comment by jadolg** [comment]
Oh, that's not very intuitive, but I get it now. Probably not to make a list of of the exclude parameter.
Thanks for the quick answer.

**Comment by angristan** [comment]
You're welcome. Thanks for the issue + PR. I agree, it's not very intuitive. :D
