### ISSUE TITLE
Does not have a meta/main.yml file

### ISSUE THREAD

**Issue by DavidOliver** [angristan/ansible-restic#6]
Hi. Judging from your blog post and the readme, this role sounds great; thanks for making it and your other roles available. I use restic (and Hetzner and PostgreSQL), so would very much like to try using this role for a new webserver.

I haven't used a third-party Ansible role before. I put this in `roles/requirements.yml`:

```yml
- src: https://github.com/angristan/ansible-restic
  version: 4364ed0801ba8e7cb1dfe00cdb93403bf6f275f3
```

I then ran `ansible-galaxy install -r roles/requirements.yml`, and got:

> [WARNING]: - ansible-restic was NOT installed successfully: this role does not appear to have a meta/main.yml file.
> ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

Assuming the file is required and should be added, I thought about submitting a pull request using https://github.com/angristan/ansible-php-fpm/blob/master/meta/main.yml as a guide, but thought you might want to specify the values yourself.

**Comment by angristan** [comment]
Ah, you're right, I forgot this since I don't publish them to ansible-galaxy anymore.

**Comment by DavidOliver** [comment]
Do you think you might publish this to ansible-galaxy? If so, let me know if you want me to add the main.yml file in a PR.

I ended up committing the role source to my ansible project.

Thanks. :)

**Comment by angristan** [comment]
👋 No, I won't publish it to Galaxy 🙂

**Comment by angristan** [comment]
I added a `meta/main.yml`!
